### ISSUE TITLE
"You must install the lxml package before you can run mypy with `--html-report`."

### ISSUE THREAD

**Issue by MartinThoma** [pre-commit/mirrors-mypy#30]
I keep getting the following error message with pre-commit:

```
You must install the lxml package before you can run mypy with `--html-report`.
You can do this with `python3 -m pip install lxml`.
Traceback (most recent call last):
  File "/home/moose/.cache/pre-commit/repordi15o4q/py_env-python3.8/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/moose/.cache/pre-commit/repordi15o4q/py_env-python3.8/lib/python3.8/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 90, in main
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 217, in _build
  File "mypy/report.py", line 58, in __init__
  File "mypy/report.py", line 71, in add_report
ImportError
```

But this works just fine:

```
$ mypy . --html-report html-mypy
Generated HTML report (via XSLT): /home/moose/GitHub/MartinThoma/minimal_symbol_recognizer/html-mypy/index.html
Success: no issues found in 5 source files
```

## System

* Ubuntu 20.04
* Python 3.8.5 via [pyenv](https://github.com/pyenv/pyenv)
* pre-commit 2.8.2 via pyenv

`.pre-commit-config.yaml`:

```
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
```

**Comment by asottile** [comment]
please read the [bottom of the README](https://github.com/pre-commit/mirrors-mypy#using-mypy-with-pre-commit) -- it's not too long and answers your question

hint: `additional_dependencies`

**Comment by MartinThoma** [comment]
Thank you!

The copyable answer is:

```
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [lxml]
```
